# create your drupal and mysql config here, based off the last assignment
version: '3'
services:
  drupal:
    image: drupal
    ports:
      - "8000:80"
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
      - drupal-data:/var/lib/postgresql/data
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_ROOT_PASSWORD=mypasswd 
volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
  drupal-data:
  